
# Industrial Plant Design Using Jupyter Notebook

## Sample project with interactive 3D visualization

This notebook demonstrates a simplified industrial process plant layout containing:

- Raw-material storage tank
- Feed pump
- Heat exchanger
- Process reactor
- Product separator
- Product storage tank
- Control room
- Pipe connections
- Safety clearance zones
- Basic engineering calculations
- Interactive 3D plant visualization using Plotly

> **Note:** This is an educational conceptual design, not a construction-ready engineering design.


## 1. Install and import libraries

Uncomment the installation command if Plotly or pandas is not installed.

In [10]:

# %pip install numpy pandas plotly

import math
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

pd.set_option("display.max_columns", None)

## 2. Define plant equipment data

In [11]:

equipment = pd.DataFrame([
    {
        "tag": "TK-101",
        "name": "Raw Material Tank",
        "type": "Vertical Tank",
        "x": 8, "y": 10, "z": 0,
        "length": 5, "width": 5, "height": 10,
        "capacity_m3": 150,
        "power_kw": 0,
        "safety_radius_m": 4
    },
    {
        "tag": "P-101",
        "name": "Feed Pump",
        "type": "Pump",
        "x": 16, "y": 10, "z": 0,
        "length": 3, "width": 2, "height": 2,
        "capacity_m3": np.nan,
        "power_kw": 18.5,
        "safety_radius_m": 1.5
    },
    {
        "tag": "E-101",
        "name": "Heat Exchanger",
        "type": "Heat Exchanger",
        "x": 23, "y": 10, "z": 1.5,
        "length": 7, "width": 3, "height": 3,
        "capacity_m3": np.nan,
        "power_kw": 5,
        "safety_radius_m": 2
    },
    {
        "tag": "R-101",
        "name": "Process Reactor",
        "type": "Vertical Reactor",
        "x": 34, "y": 10, "z": 0,
        "length": 6, "width": 6, "height": 13,
        "capacity_m3": 100,
        "power_kw": 45,
        "safety_radius_m": 5
    },
    {
        "tag": "V-101",
        "name": "Product Separator",
        "type": "Vertical Vessel",
        "x": 45, "y": 10, "z": 0,
        "length": 5, "width": 5, "height": 9,
        "capacity_m3": 65,
        "power_kw": 3,
        "safety_radius_m": 3.5
    },
    {
        "tag": "TK-102",
        "name": "Product Tank",
        "type": "Vertical Tank",
        "x": 55, "y": 10, "z": 0,
        "length": 5, "width": 5, "height": 10,
        "capacity_m3": 140,
        "power_kw": 0,
        "safety_radius_m": 4
    },
    {
        "tag": "CR-101",
        "name": "Control Room",
        "type": "Building",
        "x": 33, "y": 27, "z": 0,
        "length": 12, "width": 7, "height": 5,
        "capacity_m3": np.nan,
        "power_kw": 12,
        "safety_radius_m": 2
    }
])

equipment

,tag,name,type,x,y,z,length,width,height,capacity_m3,power_kw,safety_radius_m
0,TK-101,Raw Material Tank,Vertical Tank,8,10,0.0,5,5,10,150.0,0.0,4.0
1,P-101,Feed Pump,Pump,16,10,0.0,3,2,2,NaN,18.5,1.5
2,E-101,Heat Exchanger,Heat Exchanger,23,10,1.5,7,3,3,NaN,5.0,2.0
3,R-101,Process Reactor,Vertical Reactor,34,10,0.0,6,6,13,100.0,45.0,5.0
4,V-101,Product Separator,Vertical Vessel,45,10,0.0,5,5,9,65.0,3.0,3.5
5,TK-102,Product Tank,Vertical Tank,55,10,0.0,5,5,10,140.0,0.0,4.0
6,CR-101,Control Room,Building,33,27,0.0,12,7,5,NaN,12.0,2.0

## 3. Basic process and plant calculations

In [12]:

# Simplified design assumptions
production_rate_tph = 12.0
operating_hours_per_day = 20
operating_days_per_year = 330
plant_efficiency = 0.92
product_density_t_m3 = 0.85
electricity_cost_ksh_per_kwh = 30

daily_production_t = production_rate_tph * operating_hours_per_day * plant_efficiency
annual_production_t = daily_production_t * operating_days_per_year
daily_product_volume_m3 = daily_production_t / product_density_t_m3

total_connected_power_kw = equipment["power_kw"].sum()
daily_energy_kwh = total_connected_power_kw * operating_hours_per_day
annual_energy_kwh = daily_energy_kwh * operating_days_per_year
annual_electricity_cost_ksh = annual_energy_kwh * electricity_cost_ksh_per_kwh

summary = pd.DataFrame({
    "Metric": [
        "Effective daily production",
        "Annual production",
        "Daily product volume",
        "Total connected power",
        "Daily electrical energy",
        "Annual electrical energy",
        "Estimated annual electricity cost"
    ],
    "Value": [
        daily_production_t,
        annual_production_t,
        daily_product_volume_m3,
        total_connected_power_kw,
        daily_energy_kwh,
        annual_energy_kwh,
        annual_electricity_cost_ksh
    ],
    "Unit": [
        "tonnes/day",
        "tonnes/year",
        "m³/day",
        "kW",
        "kWh/day",
        "kWh/year",
        "KSh/year"
    ]
})

summary

                              Metric         Value         Unit
0         Effective daily production  2.208000e+02   tonnes/day
1                  Annual production  7.286400e+04  tonnes/year
2               Daily product volume  2.597647e+02       m³/day
3              Total connected power  8.350000e+01           kW
4            Daily electrical energy  1.670000e+03      kWh/day
5           Annual electrical energy  5.511000e+05     kWh/year
6  Estimated annual electricity cost  1.653300e+07     KSh/year

## 4. Storage adequacy check

In [13]:

product_tank_capacity_m3 = equipment.loc[
    equipment["tag"] == "TK-102", "capacity_m3"
].iloc[0]

storage_days = product_tank_capacity_m3 / daily_product_volume_m3

print(f"Product tank capacity: {product_tank_capacity_m3:.1f} m³")
print(f"Estimated daily product volume: {daily_product_volume_m3:.1f} m³/day")
print(f"Available product storage: {storage_days:.2f} days")

if storage_days >= 1:
    print("Result: Storage is adequate for at least one day of production.")
else:
    print("Result: Consider increasing product storage capacity.")

Product tank capacity: 140.0 m³
Estimated daily product volume: 259.8 m³/day
Available product storage: 0.54 days
Result: Consider increasing product storage capacity.

## 5. Define process pipe connections

In [14]:

pipes = pd.DataFrame([
    {"line": "L-101", "from_tag": "TK-101", "to_tag": "P-101", "diameter_mm": 100, "service": "Raw material"},
    {"line": "L-102", "from_tag": "P-101", "to_tag": "E-101", "diameter_mm": 80, "service": "Pressurized feed"},
    {"line": "L-103", "from_tag": "E-101", "to_tag": "R-101", "diameter_mm": 80, "service": "Heated feed"},
    {"line": "L-104", "from_tag": "R-101", "to_tag": "V-101", "diameter_mm": 100, "service": "Reactor effluent"},
    {"line": "L-105", "from_tag": "V-101", "to_tag": "TK-102", "diameter_mm": 80, "service": "Finished product"}
])

pipes

    line from_tag  to_tag  diameter_mm           service
0  L-101   TK-101   P-101          100      Raw material
1  L-102    P-101   E-101           80  Pressurized feed
2  L-103    E-101   R-101           80       Heated feed
3  L-104    R-101   V-101          100  Reactor effluent
4  L-105    V-101  TK-102           80  Finished product

## 6. Approximate pipe lengths and pressure-drop indicator

In [15]:

equipment_lookup = equipment.set_index("tag")

pipe_results = []

for _, pipe in pipes.iterrows():
    start = equipment_lookup.loc[pipe["from_tag"]]
    end = equipment_lookup.loc[pipe["to_tag"]]

    dx = end["x"] - start["x"]
    dy = end["y"] - start["y"]
    dz = (end["z"] + end["height"]/2) - (start["z"] + start["height"]/2)

    straight_length = math.sqrt(dx**2 + dy**2 + dz**2)
    design_length = straight_length * 1.20  # 20% allowance for routing and fittings

    # Educational pressure-drop indicator, not a full hydraulic calculation
    pressure_drop_index = design_length / (pipe["diameter_mm"] / 1000) ** 5

    pipe_results.append({
        "line": pipe["line"],
        "service": pipe["service"],
        "diameter_mm": pipe["diameter_mm"],
        "straight_length_m": round(straight_length, 2),
        "estimated_design_length_m": round(design_length, 2),
        "relative_pressure_drop_index": round(pressure_drop_index, 0)
    })

pipe_analysis = pd.DataFrame(pipe_results)
pipe_analysis

,line,service,diameter_mm,straight_length_m,estimated_design_length_m,relative_pressure_drop_index
0,L-101,Raw material,100,8.94,10.73,1073313.0
1,L-102,Pressurized feed,80,7.28,8.74,2666056.0
2,L-103,Heated feed,80,11.54,13.85,4227318.0
3,L-104,Reactor effluent,100,11.18,13.42,1341641.0
4,L-105,Finished product,80,10.01,12.01,3666684.0


## 7. Interactive 3D industrial plant model

Use your mouse to:

- Rotate the plant
- Zoom in and out
- Pan across the layout
- Hover over equipment to view engineering details
- Toggle equipment, pipes and safety zones from the legend

In [16]:

def add_box(fig, x, y, z, length, width, height, name, hover_text, opacity=0.85):
    x0, x1 = x - length/2, x + length/2
    y0, y1 = y - width/2, y + width/2
    z0, z1 = z, z + height

    vertices_x = [x0, x1, x1, x0, x0, x1, x1, x0]
    vertices_y = [y0, y0, y1, y1, y0, y0, y1, y1]
    vertices_z = [z0, z0, z0, z0, z1, z1, z1, z1]

    i = [0, 0, 0, 1, 1, 2, 4, 4, 5, 3, 2, 6]
    j = [1, 2, 4, 2, 5, 3, 5, 6, 6, 7, 3, 7]
    k = [2, 4, 5, 5, 6, 7, 6, 7, 1, 4, 7, 3]

    fig.add_trace(go.Mesh3d(
        x=vertices_x,
        y=vertices_y,
        z=vertices_z,
        i=i, j=j, k=k,
        name=name,
        hovertext=hover_text,
        hoverinfo="text",
        opacity=opacity,
        flatshading=True,
        showlegend=True
    ))


def add_vertical_vessel(fig, x, y, z, diameter, height, name, hover_text):
    theta = np.linspace(0, 2*np.pi, 50)
    z_values = np.linspace(z, z + height, 30)
    theta_grid, z_grid = np.meshgrid(theta, z_values)

    radius = diameter / 2
    x_grid = x + radius * np.cos(theta_grid)
    y_grid = y + radius * np.sin(theta_grid)

    fig.add_trace(go.Surface(
        x=x_grid,
        y=y_grid,
        z=z_grid,
        name=name,
        hovertext=hover_text,
        hoverinfo="text",
        showscale=False,
        opacity=0.90,
        showlegend=True
    ))

    # Top head
    fig.add_trace(go.Mesh3d(
        x=x + radius * np.cos(theta),
        y=y + radius * np.sin(theta),
        z=np.full_like(theta, z + height),
        name=f"{name} top",
        hoverinfo="skip",
        opacity=0.90,
        showlegend=False
    ))


fig = go.Figure()

# Plant floor
floor_x = [0, 65, 65, 0]
floor_y = [0, 0, 35, 35]
floor_z = [0, 0, 0, 0]

fig.add_trace(go.Mesh3d(
    x=floor_x,
    y=floor_y,
    z=floor_z,
    i=[0, 0],
    j=[1, 2],
    k=[2, 3],
    name="Plant floor",
    opacity=0.25,
    hoverinfo="skip",
    showlegend=True
))

# Equipment
for _, row in equipment.iterrows():
    hover = (
        f"<b>{row['tag']} — {row['name']}</b><br>"
        f"Type: {row['type']}<br>"
        f"Position: ({row['x']}, {row['y']}, {row['z']}) m<br>"
        f"Dimensions: {row['length']} × {row['width']} × {row['height']} m<br>"
        f"Power: {row['power_kw']} kW<br>"
        f"Capacity: {row['capacity_m3']} m³"
    )

    if row["type"] in ["Vertical Tank", "Vertical Reactor", "Vertical Vessel"]:
        add_vertical_vessel(
            fig,
            row["x"], row["y"], row["z"],
            row["length"], row["height"],
            row["tag"],
            hover
        )
    else:
        add_box(
            fig,
            row["x"], row["y"], row["z"],
            row["length"], row["width"], row["height"],
            row["tag"],
            hover
        )

# Pipe routes
for _, pipe in pipes.iterrows():
    start = equipment_lookup.loc[pipe["from_tag"]]
    end = equipment_lookup.loc[pipe["to_tag"]]

    start_z = start["z"] + start["height"] * 0.55
    end_z = end["z"] + end["height"] * 0.55
    elevated_z = max(start_z, end_z, 3.5)

    route_x = [start["x"], start["x"], end["x"], end["x"]]
    route_y = [start["y"], start["y"], end["y"], end["y"]]
    route_z = [start_z, elevated_z, elevated_z, end_z]

    fig.add_trace(go.Scatter3d(
        x=route_x,
        y=route_y,
        z=route_z,
        mode="lines+markers",
        line={"width": max(3, pipe["diameter_mm"] / 18)},
        marker={"size": 3},
        name=pipe["line"],
        text=(
            f"{pipe['line']}<br>"
            f"{pipe['service']}<br>"
            f"Diameter: {pipe['diameter_mm']} mm"
        ),
        hoverinfo="text"
    ))

# Safety-clearance circles
theta = np.linspace(0, 2*np.pi, 100)

for _, row in equipment.iterrows():
    if row["safety_radius_m"] > 0:
        fig.add_trace(go.Scatter3d(
            x=row["x"] + row["safety_radius_m"] * np.cos(theta),
            y=row["y"] + row["safety_radius_m"] * np.sin(theta),
            z=np.full_like(theta, 0.08),
            mode="lines",
            line={"width": 3, "dash": "dash"},
            name=f"{row['tag']} safety zone",
            hovertext=f"{row['tag']} safety radius: {row['safety_radius_m']} m",
            hoverinfo="text",
            visible="legendonly"
        ))

# Equipment labels
fig.add_trace(go.Scatter3d(
    x=equipment["x"],
    y=equipment["y"],
    z=equipment["z"] + equipment["height"] + 1,
    mode="text",
    text=equipment["tag"],
    textposition="top center",
    name="Equipment labels",
    hoverinfo="skip"
))

fig.update_layout(
    title={
        "text": "Interactive 3D Industrial Process Plant",
        "x": 0.5
    },
    scene={
        "xaxis_title": "Plant length (m)",
        "yaxis_title": "Plant width (m)",
        "zaxis_title": "Height (m)",
        "aspectmode": "data",
        "camera": {
            "eye": {"x": 1.7, "y": 1.7, "z": 1.25}
        }
    },
    height=750,
    margin={"l": 0, "r": 0, "b": 0, "t": 60},
    legend={
        "itemsizing": "constant"
    }
)

fig.show()

## 8. Equipment power chart

In [17]:

power_data = equipment[equipment["power_kw"] > 0].sort_values("power_kw")

power_fig = go.Figure(go.Bar(
    x=power_data["power_kw"],
    y=power_data["tag"] + " — " + power_data["name"],
    orientation="h",
    text=power_data["power_kw"].astype(str) + " kW",
    textposition="auto"
))

power_fig.update_layout(
    title="Connected Electrical Load by Equipment",
    xaxis_title="Power (kW)",
    yaxis_title="Equipment",
    height=450
)

power_fig.show()

## 9. Simple plant-layout safety check

In [18]:

safety_checks = []

for i, item_a in equipment.iterrows():
    for j, item_b in equipment.iterrows():
        if j <= i:
            continue

        centre_distance = math.sqrt(
            (item_b["x"] - item_a["x"])**2 +
            (item_b["y"] - item_a["y"])**2
        )

        required_distance = item_a["safety_radius_m"] + item_b["safety_radius_m"]
        clearance = centre_distance - required_distance

        safety_checks.append({
            "equipment_a": item_a["tag"],
            "equipment_b": item_b["tag"],
            "centre_distance_m": round(centre_distance, 2),
            "combined_safety_radius_m": round(required_distance, 2),
            "clearance_margin_m": round(clearance, 2),
            "status": "PASS" if clearance >= 0 else "REVIEW"
        })

safety_report = pd.DataFrame(safety_checks)
safety_report.sort_values("clearance_margin_m").reset_index(drop=True)

,equipment_a,equipment_b,centre_distance_m,combined_safety_radius_m,clearance_margin_m,status
0,TK-101,P-101,8.00,5.5,2.50,PASS
1,R-101,V-101,11.00,8.5,2.50,PASS
2,V-101,TK-102,10.00,7.5,2.50,PASS
3,P-101,E-101,7.00,3.5,3.50,PASS
4,E-101,R-101,11.00,7.0,4.00,PASS
5,TK-101,E-101,15.00,6.0,9.00,PASS
6,R-101,CR-101,17.03,7.0,10.03,PASS
7,P-101,R-101,18.00,6.5,11.50,PASS
8,R-101,TK-102,21.00,9.0,12.00,PASS
9,V-101,CR-101,20.81,5.5,15.31,PASS
10,E-101,CR-101,19.72,4.0,15.72,PASS
11,E-101,V-101,22.00,5.5,16.50,PASS
12,TK-101,R-101,26.00,9.0,17.00,PASS
13,P-101,CR-101,24.04,3.5,20.54,PASS
14,TK-102,CR-101,27.80,6.0,21.80,PASS
15,P-101,V-101,29.00,5.0,24.00,PASS
16,TK-101,CR-101,30.23,6.0,24.23,PASS
17,E-101,TK-102,32.00,6.0,26.00,PASS
18,TK-101,V-101,37.00,7.5,29.50,PASS
19,P-101,TK-102,39.00,5.5,33.50,PASS
20,TK-101,TK-102,47.00,8.0,39.00,PASS


## 10. Suggested project extensions

A more advanced industrial plant-design notebook could include:

1. Mass and energy balances
2. Pump sizing and hydraulic calculations
3. Pipe pressure-drop calculations using Darcy–Weisbach
4. Heat-exchanger sizing
5. Reactor design calculations
6. Equipment cost estimation
7. Plant CAPEX and OPEX model
8. Instrumentation and control-loop design
9. Piping and Instrumentation Diagram data
10. Hazard and operability study
11. Fire-water and emergency-system layout
12. Optimization of equipment positions
13. Real-time process simulation
14. Export of the layout to CAD-compatible formats


## Conclusion

This notebook provides a conceptual industrial plant design workflow using Python and Jupyter Notebook. The interactive 3D model can be rotated, zoomed and inspected, making it suitable as a foundation for an engineering or data-science portfolio project.